### ISSUE TITLE
Use mop for describe-object method

### ISSUE THREAD

**Issue by kilianmh** [40ants/openrpc#12]
The `describe-object` is now a bit weird after PR #11. See https://github.com/40ants/openrpc/blob/ab7cdd7f2a483216406104c6dda1b395d129f7a1/t/client/regress-data/multiple-types/client-class.lisp#L5

The  result should probably be something like this:
```lisp
(format stream "- ~S~%" '(example ((name null)))
(format stream "- ~S~%" '(example ((name string)))
```

One solution would be to export a function like the following that uses the `mop` and collects the information at run time (instead of hardcoding from the spec like currently):
```lisp
  (defun generate-method-descriptions (class stream)
    (flet ((proper-lambda-list (method)
             (let* ((lambda-list (closer-mop:method-lambda-list method))
                    (specializers (closer-mop:method-specializers method))
                    (list-element 0)
                    (method-name (intern (symbol-name
                                          (closer-mop:generic-function-name
                                           (closer-mop:method-generic-function method)))))
                    (lambda-list-parameters
                      (mapcar (lambda (element)
                                (let ((type
                                        (nth (incf list-element) specializers)))
                                  (if type
                                      (list (intern (symbol-name element))
                                            (intern (symbol-name (class-name type))))
                                      (typecase element
                                        (symbol
                                         (intern (symbol-name element)))
                                        (cons
                                         (mapcar (lambda (item)
                                                   (intern (symbol-name item)))
                                                 element))))))
                              (cdr lambda-list))))
               (unless (string-equal method-name 'describe-object)
                 (format stream "- ~S~%"
                         (if lambda-list-parameters
                             (list method-name lambda-list-parameters)
                             (list method-name)))))))
      (format stream "Supported RPC methods:~2%")
      (mapc #'proper-lambda-list
            (closer-mop:specializer-direct-methods class))
      nil))
```
First we generate a client from the spec.json in the testing folder
```lisp
(openrpc-client:generate-client
   test-client 
   (asdf:system-relative-pathname
    "openrpc-client"
    "t/client/regress-data/multiple-types/spec.json"))
```
Then we can redefine`describe-object` method in this way:
```lisp
(defmethod describe-object ((client test-client) stream)
    (generate-method-descriptions (class-of client) stream))
```
Now the result of
```lisp
(describe-object (make-test-client) *standard-output*)
```
should be this:
```lisp
Supported RPC methods:

- (EXAMPLE ((NAME NULL)))
- (EXAMPLE ((NAME STRING)))
```

If there are any questions, go ahead! If you like the idea, I will start a PR for this.

**Comment by svetlyak40wt** [comment]
This is is a great idea, but not all CLOS methods are RPC methods. For example, `describe-object` is not. You'll need to find out how to filter and show only real RPC methods. Also, It would be nice to sort them alphabetically.

**Comment by kilianmh** [comment]
>  not all CLOS methods are RPC methods. For example, describe-object is not. You'll need to find out how to filter and show only real RPC methods.

There is already `(unless (string-equal method-name 'describe-object)` to avoid describe-object being included. Are there others that should be excluded?

> It would be nice to sort them alphabetically.

To achieve that we can replace `(closer-mop:specializer-direct-methods class)` with
```lisp
  (stable-sort (copy-list (closer-mop:specializer-direct-methods class))
               (lambda (method1 method2)
                 (string-lessp (closer-mop:generic-function-name
                                (closer-mop:method-generic-function method1))
                               (closer-mop:generic-function-name
                                (closer-mop:method-generic-function method2)))))
```

Some other questions regarding the resulting output:
Do you still like the formatting? Should the client be mentioned as first parameter in all the methods? Should the first line include the class-name?

**Comment by kilianmh** [comment]
One more consideration is whether `generate-method-descriptions` should be a exported function (on which the generated libraries depend then), or if it should be a macro (avoid that generated libraries depend on `openrpc-client`)

**Comment by svetlyak40wt** [comment]
There is no such thing like "generated library", because the code of the library need to depend on `openrcp-client` because code expansion happens during the library compilation. Contrary for other languages often there is an additional phase of generation sources from the spec. With Common Lisp we don't have this additional phase.

I don't think we need to export `generate-method-descriptions` right now.

**Comment by svetlyak40wt** [comment]
Talking about formatting, I'm ok with what you have shown and don't think it makes sense to show the client as the first argument.
