### ISSUE TITLE
Where do I find clack-prometheus?

### ISSUE THREAD

**Issue by atgreen** [40ants/openrpc#24]
It's a build dependency for the server, but I can't find it.

**Comment by svetlyak40wt** [comment]
It should be available from Ultralisp: https://ultralisp.org/projects/40ants/clack-prometheus

Or you can clone it from the GitHub.

**Comment by atgreen** [comment]
Great -- thanks.  Strangely, google doesn't come up with this when I search for "clack-prometheus".

**Comment by svetlyak40wt** [comment]
I need to put more efforts into the Search Engine Optimization of both 40ants.com and ultralisp.org.

This is in my plans for 2024.
