### ISSUE TITLE
`"type":  ["string", "null"]` is not supported

### ISSUE THREAD

**Issue by link2xt** [40ants/openrpc#3]
This is a valid type which is even present as an example in the JSON Schema specification: https://json-schema.org/draft/2020-12/json-schema-core.html#section-7.6.1-4 This type corresponds to `Option<String>` type in Rust when generated by [`schemars` crate](https://docs.rs/schemars/) used by [`yerpc` crate](https://github.com/deltachat/yerpc/).

However, currently `openrpc-client/core::schema-to-type` fails because it tries to use `string-equal` to compare `("string" "null")` to `"integer"` and does not even get to `"Type ~S is not supported yet."` error:
https://github.com/40ants/openrpc/blob/c5c431d05691b18e3cf4d44f447e3c8fc0d197b5/client/core.lisp#L55-L64

**Comment by svetlyak40wt** [comment]
Please, provide a minimal code to reproduce the problem.

**Comment by link2xt** [comment]
Here is a minimal example that results in this error:
```json
{
  "openrpc": "1.0.0",
  "info": {
    "version": "1.0.0",
    "title": "API"
  },
  "methods": [
    {
      "name": "set_config",
      "params": [
        {
          "name": "key",
          "schema": {
            "type": "string"
          },
          "required": true
        },
        {
          "name": "value",
          "schema": {
            "type": [
              "string",
              "null"
            ]
          },
          "required": true
        }
      ],
      "result": {
        "name": "SetConfigResult",
        "schema": {
          "type": "null"
        },
        "required": true
      },
      "paramStructure": "by-position"
    }
  ]
}
```

"null" result may be another problem, but generation did not get to this point.

```lisp
(ql:quickload "openrpc-client")
(openrpc-client:generate-client client ".../openrpc.json")
```
